### ISSUE TITLE
Could you create a version of the plugin that will be compatible with CS2 Weapon Paints?

### ISSUE THREAD

**Issue by K0v47** [oqyh/cs2-Knife-Round#3]
When the CS2 Weapon Paints plugin is installed, for changing skins, there is no knife from the plugin on the knife round. The easiest way would be to give each player a Glock-18 without ammunition. CS2 weapon paint has a problem with loading a knife when there is no other weapon in the inventory
PS. sorry for my english, I use google translator

**Comment by oqyh** [comment]
> When the CS2 Weapon Paints plugin is installed, for changing skins, there is no knife from the plugin on the knife round. The easiest way would be to give each player a Glock-18 without ammunition. CS2 weapon paint has a problem with loading a knife when there is no other weapon in the inventory PS. sorry for my english, I use google translator

it compatible  with Weapon Paints

plugin knife start > remove except knife (Weapon Paint)
https://github.com/oqyh/cs2-Knife-Round/blob/dc0dde16252d5041c1a5677d6da84c8a11228053/knife_round.cs#L108C29-L108C133

after wining knife round plugin will stop

**Comment by oqyh** [comment]
check plugins you have what cause that

**Comment by oqyh** [comment]
closing no reply
