### ISSUE TITLE
Evolution

### ISSUE THREAD

**Issue by Armageddon87270** [oqyh/cs2-Knife-Round#4]
Hi,

Your plugins are great thank you. Can you upgrade your plugins? 
- Ability to deactivate plugins depending on the bots 
- Possibility of having a minimum number of players

Example:
"Minimum players": 6,
 "Count bots as players": false,

Thx

**Comment by oqyh** [comment]
> Hi,
> 
> Your plugins are great thank you. Can you upgrade your plugins?
> 
> * Ability to deactivate plugins depending on the bots
> * Possibility of having a minimum number of players
> 
> Example: "Minimum players": 6, "Count bots as players": false,
> 
> Thx

download [CS2] Knife Round GoldKingZ (1.1.1)

**Comment by Armageddon87270** [comment]
Hi,

If you set MinimumPlayersToEnableKnifePlugin = 6 and you are alone it's ok but when changing maps is that you are 6 your plugins no longer work

**Comment by oqyh** [comment]
> Hi,
> 
> If you set MinimumPlayersToEnableKnifePlugin = 6 and you are alone it's ok but when changing maps is that you are 6 your plugins no longer work

plugin will count players when warmup end if not pass MinimumPlayersToEnableKnifePlugin plugin will ignored

**Comment by Armageddon87270** [comment]
So it doesn't work, write me the message on the first maps but not on the second maps

**Comment by oqyh** [comment]
> So it doesn't work, write me the message on the first maps but not on the second maps

[CS2] Knife Round GoldKingZ (1.1.2) Should Work

**Comment by Armageddon87270** [comment]
Hi,
yes it works you can avoid restarting the game when the plugins are deactivated

**Comment by oqyh** [comment]
> Hi, yes it works you can avoid restarting the game when the plugins are deactivated

restart to respawn default game mode (c4, timers, etc...) without it will be buggy

**Comment by Armageddon87270** [comment]
ok, but as there are not enough of us so plugins don't work for me no need to restart (I'm telling you this because it conflicts with bomb restrict)

**Comment by oqyh** [comment]
> ok, but as there are not enough of us so plugins don't work for me no need to restart (I'm telling you this because it conflicts with bomb restrict)

[CS2] Knife Round GoldKingZ (1.1.3) should do the job

**Comment by oqyh** [comment]
> ok, but as there are not enough of us so plugins don't work for me no need to restart (I'm telling you this because it conflicts with bomb restrict)

you can close this issue once everything ok

**Comment by oqyh** [comment]
> ok, but as there are not enough of us so plugins don't work for me no need to restart (I'm telling you this because it conflicts with bomb restrict)

closing this issue for no respond

**Comment by Armageddon87270** [comment]
Hi sorry gone for the weekend, it's perfect everything works perfectly, for your maps configurator plugins you should be able to deactivate the round cut plugins according to the name of the maps to avoid bugs from poorly configured maps. great job I will make a donation to you soon.

**Comment by oqyh** [comment]
> Hi sorry gone for the weekend, it's perfect everything works perfectly, for your maps configurator plugins you should be able to deactivate the round cut plugins according to the name of the maps to avoid bugs from poorly configured maps. great job I will make a donation to you soon.

you can join our disocrd and download dev version of map config plugin it has gkz_load / gkz_unload custom covar to load / unload any plugin depend map name
